name: Terraform Plan
on:
    pull_request:
        branches: 
        - 

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4
        -   name: setup terraform
            uses: hashicorp/setup-terraform@v3
        -   name: Configure AWS Credentials (Role 1)
            uses: aws-actions/configure-aws-credentials@v4
            with:
                role-to-assume: arn:aws:iam::184471688725:role/s3_git_role
                aws-region: us-east-1
        -   name: Terraform init
            run: Terraform init
        -   name: Terraform plan
            run: terraform plan

