name: Terraform Plan

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main


jobs:
  plan:
    uses: vallikatakamsetti-crypto/terraform-reusable/.github/workflows/terraform-reusable.yml@main
    with:
      terraform-command: "plan"
      aws-region: us-east-1
    secrets:
      role-to-assume: ${{ secrets.IAM_GHA_ROLE }}