name: Terraform Apply

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  plan:
    uses: vallikatakamsetti-crypto/terraform-reusable/.github/workflows/terraform-reusable.yml@main
    with:
      terraform-command: "apply --auto-approve"
      role-to-assume: arn:aws:iam::042360978040:role/gha-role
      aws-region: us-east-1
    secrets: inherit